apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ithgdftg
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/sjmrhtap/go-ithgdftg:87d0fc3ae6d075d93b252526c1f9420309f12447
        name: container-image  
